services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    env_file: .env
    ports:
      - "11434:11434"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - BASE_MODEL=${BASE_MODEL}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      retries: 5
    volumes:
      - ./ollama-entrypoint.sh:/usr/local/bin/ollama-entrypoint.sh
      - ollama_models:/root/.ollama
      - ./ai-comply-modelfile:/tmp/ai-comply-modelfile
    entrypoint: ["/usr/local/bin/ollama-entrypoint.sh"]

  openwebui:
    image: ghcr.io/open-webui/open-webui
    container_name: openwebui
    env_file: .env
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_HOST}
      - LISTEN_ADDR=0.0.0.0
    depends_on:
      - ollama
    volumes:
      - open-webui-data:/app/backend/data
      - ./rag-documents:/app/backend/data/docs/external_bind_mounts:ro
      - ./openwebui-entrypoint.sh:/usr/local/bin/openwebui-entrypoint.sh

volumes:
  ollama_models:
  open-webui-data: